[package]
name = "rust_option_enum"
version = "0.1.0"
authors = ["ReginaF2012 <skritschy@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
